name: Remove Center Alignment

on: 
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - readme.md
      - '**/**'
    paths:
      - '*.md'
    
jobs:
  remove-center-alignment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.head_commit.id }}

      - name: Remove align="center" from Markdown file
        run: |
          MODIFIED_FILE=${{ github.event.head_commit.modified }}
          sed -i 's/ align="center"//g' "$MODIFIED_FILE"

      - name: Amend Commit Message
        run: |
          git commit --amend --no-edit
          git push --force
