name: Remove align center

on:
  push:
    paths:
      - '**.md'
      - '!README.md'
      - '!readme.md'

jobs:
  remove-align-center:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get latest commit file
      id: latest_commit
      run: |
        echo "Getting latest commit file..."
        echo $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | head -1)"
        COMMITTED_FILE="$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | head -1)"
        echo "COMMITTED_FILE=$COMMITTED_FILE" >> $GITHUB_ENV
        
    - name: Remove align center from committed Markdown file
      run: |
        echo "Removing align center from committed Markdown file..."
        sed -i 's/ align="center"//g' "${{ env.COMMITTED_FILE }}"
        cat "${{ env.COMMITTED_FILE }}"
        git diff "${{ env.COMMITTED_FILE }}"
        
    - name: Configure Git user
      run: |
        echo "Configuring Git user..."
        git config --global user.email "noreply@github.com"
        git config --global user.name "cdrani"

    - name: Commit changes
      run: |
        echo "Amending commit..."
        echo "Changes in working tree:"
        git diff "${{ env.COMMITTED_FILE }}"
        git add "${{ env.COMMITTED_FILE }}"
        grep 'align="center"' "${{ env.COMMITTED_FILE }}"
        git commit -m '[automated] remove center alignment in ${{ env.COMMITTED_FILE }}'

    - name: Push changes
      run: |
        echo "Pushing changes..."
        git push


