name: Remove align center

on:
  push:
    paths:
      - '**.md'
      - '!README.md'
      - '!readme.md'

jobs:
  remove-align-center:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Print repository state
      run: |
        echo "Current repository state:"
        git status
        git log -n 1 --pretty=format:"%h %s"  
        git show --pretty="" --name-only
      
    - name: Get latest commit file
      id: latest_commit
      run: |
        echo "Getting latest commit file..."
        asha=${{ github.event.after }}
        bsha=${{ github.event.before }}
        echo "BEFORE:: $(git diff --name-only $bsha $asha)"
        echo "CURRENT:: $(git diff --name-only $bsha ${{ github.sha }})"
        echo "AFTER:: $(git log -n 1 --name-only -U0 --pretty=format:'' $asha)"

#     - name: Get latest commit file
#       id: latest_commit
#       run: |
#         echo "Getting latest commit file..."
#         asha=${{ github.event.after }}
#         bsha=${{ github.event.before }}
#         # echo "$(git log -n 1 --name-only --pretty=format:'' $sha | cat)"
        
#         echo "BEFORE:: $(git log -n 1 --name-only -U0 --pretty=format:'' $asha)"
#         echo "CURRENT:: $(git log -n 1 --name-only -U0 --pretty=format:'' ${{ github.sha }})"
#         echo "AFTER:: $(git log -n 1 --name-only -U0 --pretty=format:'' $asha)"

#         # COMMITTED_FILE="$(git log -n 1 --name-only --pretty=format:'' $sha | tail -n1)"
#         # echo "$sha"
#         # echo "$COMMITTED_FILE"
#         # echo "COMMITTED_FILE=$COMMITTED_FILE" >> $GITHUB_ENV
        
#     - name: Remove align center from committed Markdown file
#       run: |
#         echo "Removing align center from committed Markdown file..."
#         sed -i 's/ align="center"//g' "${{ env.COMMITTED_FILE }}"
#         cat "${{ env.COMMITTED_FILE }}"
#         git diff "${{ env.COMMITTED_FILE }}"
        
#     - name: Configure Git user
#       run: |
#         echo "Configuring Git user..."
#         git config --global user.email "noreply@github.com"
#         git config --global user.name "cdrani"

#     - name: Commit changes
#       run: |
#         echo "Amending commit..."
#         echo "Changes in working tree:"
#         git diff "${{ env.COMMITTED_FILE }}"
#         git add "${{ env.COMMITTED_FILE }}"
#         grep 'align="center"' "${{ env.COMMITTED_FILE }}"
#         git commit -m '[automated] remove center alignment in ${{ env.COMMITTED_FILE }}'

#     - name: Push changes
#       run: |
#         echo "Pushing changes..."
#         git push


